apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-write-app
  template:
    metadata:
      labels:
        app: my-write-app
    spec:
      containers:
        - name: my-write
          image: python:write
          command: ["python", "script.py"]
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
              secretKeyRef:
                name: azure_srorage
                key: string
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      